name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create file list 
        id : files_list
        run: echo "::set-output name=files::$(pwsh ./create-filelist-for-github-action-fr.ps1)"

      - uses: docker://pandoc/latex:2.9
        with:
            args:  --output=output/abteilungswe-v3-fr.pdf ${{ steps.files_list.outputs.files }} --toc -V toc-title:"Inhaltsverzeichnis" -V linkcolor:blue -V geometry:a4paper -V geometry:margin=2cm -V fontsize=12pt --pdf-engine=xelatex --template=Source/_tools/template.tex
      - uses: actions/upload-artifact@master
        with:
            name: pdf
            path: output/abteilungswe-v3.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/abteilungswe-v3-fr.pdf

      - name: Automatic Pre-Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Hier gibt's die neuste PDF"
          files: |
            output/abteilungswe-v3-fr.pdf